feat: add Google Cloud Storage support (GCS)
openedx/edx-ora2 pull request #2193
Opened 2024-03-17 07:10 UTC by shadinaif

**TL;DR -** [ A short summary of what this PR does and why ]

JIRA: [JIRA-XXXX](https://openedx.atlassian.net/browse/JIRA-XXXX)

**What changed?**

- [ More in depth breakdown of changes ]
- [ Peripheral things that got changed ]
- [ etc... ]

**Developer Checklist**

- [ ] Reviewed the [release process](https://github.com/openedx/edx-ora2/blob/master/.github/release_process.md)
- [ ] Translations and JS/SASS compiled
- [ ] Bumped version number in [openassessment/\_\_init\_\_.py](https://github.com/openedx/edx-ora2/blob/master/openassessment/__init__.py#L4) and [package.json](https://github.com/openedx/edx-ora2/blob/master/package.json#L3)

**Testing Instructions**

[ How should a reviewer test this PR? ]

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ] I've done a visual code review
- [ ] I've tested the new functionality

FYI: @openedx/content-aurora

2024-03-17 07:10 UTC, openedx-webhooks commented
Thanks for the pull request, @shadinaif! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2024-03-22 09:30 UTC, itsjeyd commented
@shadinaif Thank you for this contribution! Let us know when the changes are ready for review.

2024-04-22 09:07 UTC, shadinaif commented
Thank you for the reminder @itsjeyd . Yes, it's on production and working fine. I'll rebase and set to review soon

2024-04-26 07:25 UTC, itsjeyd commented
@shadinaif Sounds good, thanks for the update.

2024-05-23 15:01 UTC, itsjeyd commented
Hey @shadinaif, do you have any updates about when you'll be able to come back to this PR?

2024-05-25 13:06 UTC, shadinaif commented
Thanks for the follow-up @itsjeyd , I'll get back to it and complete it on Tuesday, June 4, 2024 I promise. I've added it to my schedule. Sorry for the delay 🙏🏼

2024-05-31 07:21 UTC, itsjeyd commented
Sounds good, thanks for the update @shadinaif.

2024-06-06 07:57 UTC, itsjeyd commented
@shadinaif It looks like tests will need some further tweaking here. Could you have a look?

2024-06-26 11:39 UTC, itsjeyd commented
Hey @shadinaif, thanks for working on the tests.

It looks like some of them are still failing. Will you be taking another look?

2024-06-26 20:54 UTC, shadinaif commented
Thanks for the reminder @itsjeyd , I'll do in a couple of days 👍🏼

2024-07-18 15:06 UTC, itsjeyd commented
@shadinaif Just checking in to see if you're still planning to continue working on this PR? If you don't think you'll get to it in the short term, it might make sense to close it for the time being.

2024-07-26 15:14 UTC, shadinaif commented on tox.ini
> +    pytest {posargs}
this is not related to the PR, it just makes it easier to run test for a single file or object locally

2024-07-27 15:39 UTC, shadinaif commented
@itsjeyd thank you for your patience on this. I've added the needed tests, and I also had to fix some linter errors not related to the PR. All green now

2024-08-08 06:54 UTC, itsjeyd commented
@shadinaif Great! I'm marking this PR as ready for review now.

2024-08-12 14:01 UTC, feanil commented
Added the team to the repo and tagged them for review.

2024-09-10 06:17 UTC, pomegranited requested changes
Hi @shadinaif , I'm having trouble getting Google Cloud credentials configured to test this change. Are you planning to submit a GCS integration PR to the platform? 

I found [documentation](https://django-storages.readthedocs.io/en/latest/backends/gcloud.html) for initializing the `GS_CREDENTIALS` setting, but since it requires initializing that setting as a `google.oauth2.service_account.Credentials` object, I can't configure it with yml, and would have to modify the platform's `envs/*.py` files.

And without platform integration, I don't think we should add it to ORA2 either. Open to discussion though, let me know?

2024-09-20 12:26 UTC, itsjeyd commented
Thanks for picking up the review for this PR @pomegranited!

2024-10-17 07:38 UTC, itsjeyd commented
Hey @shadinaif, just checking in to see if you're still planning to continue working on this PR?

2024-10-17 07:53 UTC, shadinaif commented
Hi @itsjeyd , looks like I missed the notification for the review. I'll continue with it on the weekend. Thank you for the ping!

2024-11-14 10:40 UTC, itsjeyd commented
Hi @shadinaif, it's been about a month without any activity here, so I'm closing this PR for now. Feel free to reopen it (or open a new one) when you're ready to come back to this work.

2024-11-14 10:40 UTC, closed without merging