Added Notifications for staff.
openedx/edx-ora2 pull request #2201
Opened 2024-04-03 07:02 UTC by AhtishamShahid

To implement notiifcation for staff installed openedx-events and created signal for notification when\ever there is new submission , and next step in work flow is staff grading.

2024-04-08 09:53 UTC, asadazam93 approved these changes

2024-04-08 09:54 UTC, asadazam93 requested changes
Tests are failing

2024-04-18 12:16 UTC, asadazam93 approved these changes

2024-04-22 07:01 UTC, muhammadadeeltajamul approved these changes

2024-04-22 08:17 UTC, saadyousafarbi approved these changes
looks good!
there seems to be a conflict, can you please resolve that? Thanks!

2024-04-22 09:05 UTC, merged