Disable uploading files while an upload is in progress
openedx/edx-ora2 pull request #2237
Opened 2024-09-26 10:36 UTC by viadanna

This PR disables the upload button and shows a spinner during uploads so continuing to click the upload button doesn't flood the LMS with requests.

**What changed?**

- Disables the Upload Files button when upload starts.
- Shows a spinner to indicate to the learner an upload is in progress.
- Toggle both when the upload finishes or fails.

**Developer Checklist**

- [x] Reviewed the [release process](https://github.com/openedx/edx-ora2/blob/master/.github/release_process.md)
- [x] Translations and JS/SASS compiled
- [x] Bumped version number in [openassessment/\_\_init\_\_.py](https://github.com/openedx/edx-ora2/blob/master/openassessment/__init__.py#L4) and [package.json](https://github.com/openedx/edx-ora2/blob/master/package.json#L3)

**Testing Instructions**

1. Deploy this version of the xblock to a devstack or instance.
2. Create a course and add the xblock.
3. Edit the xblock settings to allow uploads.
4. Go to the xblock in the LMS.
5. Open the browser developer console and set throttling to 3G.
6. Select a few files and click Upload files.
7. Confirm the button is disabled and a spinner appears.
8. Disable throttling in the developer console.
9. Confirm the button is enabled again and the spinner disappears when the upload finishes.

**Reviewer Checklist**

Collectively, these should be completed by reviewers of this PR:

- [ ] I've done a visual code review
- [ ] I've tested the new functionality

FYI: @openedx/content-aurora

2024-09-26 10:36 UTC, openedx-webhooks commented
Thanks for the pull request, @viadanna!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@openedx/2u-aurora`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2024-10-11 09:50 UTC, itsjeyd commented
@viadanna Since this is a user-facing change it will need to go through product review. You can get that process started by creating a product proposal and pinging `#wg-product-core` on Slack to find a coordinator (cf. [docs](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process)).

CC @kaustavb12

2024-10-31 00:39 UTC, pomegranited commented
@viadanna @kaustavb12 Once Product is done with their review, feel free to ping me for a CC review & merge.

2024-11-21 13:45 UTC, itsjeyd commented
Hey @viadanna, checking in to see if you've had a chance yet to ping `#wg-product-core` on Slack to find a coordinator for the product proposal (https://github.com/openedx/platform-roadmap/issues/387) for this PR?

2024-11-22 23:44 UTC, viadanna commented
@itsjeyd Yes, I did, but got no answer yet.

2025-06-27 11:43 UTC, viadanna commented
@pomegranited this is good for CC review.

2025-06-29 08:55 UTC, pomegranited requested changes
Hi @viadanna, this is working great, thank you for this fix!

One nit on styles, but I can approve once that's fixed.

:+1:

- [x] I tested this using the demoX course's [ORA block](http://apps.local.openedx.io:2000/learning/course/course-v1:OpenedX+DemoX+DemoCourse/block-v1:OpenedX+DemoX+DemoCourse+type@sequential+block@e2206f6f2cd449ab85a7aa424fd0fb72/block-v1:OpenedX+DemoX+DemoCourse+type@vertical+block@f0aa93365d264e2fb14dc9c1b5efa976)
- [x] I read through the code
- [x] I checked for accessibility issues by using my keyboard to navigate and checking the aria tags
- [x] Includes documentation
- [x] <strike>User-facing strings are extracted for translation</strike> N/A

2025-06-29 08:55 UTC, pomegranited commented on openassessment/templates/legacy/response/oa_response.html
> +                                  <span class="icon fa fa-spinner fa-spin is--hidden" aria-hidden="true"></span>
This is working great, but the `is--hidden` style isn't working so well, so the spinner is causing the button text to be off center:

![image](https://github.com/user-attachments/assets/49245d06-8da5-439e-84e7-1cdea9dddf4d)

Could you update [`%state-hidden`](https://github.com/openedx/edx-ora2/blob/3418d7b74e0a20d6ced041dc0e0175b300f32934/openassessment/xblock/static/sass/xb/utilities/_extends.scss#L124) to make `display: none !important;`?

2025-07-02 08:25 UTC, viadanna commented on openassessment/templates/legacy/response/oa_response.html
> +                                  <span class="icon fa fa-spinner fa-spin is--hidden" aria-hidden="true"></span>
Sure @pomegranited done :+1:

2025-07-03 09:39 UTC, pomegranited approved these changes
Thank you for that fix @viadanna , it's working perfectly now.

2025-07-03 09:39 UTC, merged

2025-08-13 13:55 UTC, viadanna commented
@pomegranited are you able to create a new release from the tag `6.16.4` so we can bump this on master?