edx-ora2 | Replace pkg_resources to importlib_resources | Drop support for python 3.8
openedx/edx-ora2 pull request #2238
Opened 2024-09-30 07:04 UTC by ttqureshi

# Overview
This PR:
- replaces `pkg_resources` api from `importlib_resources` api
- drops support for `python 3.8` and add support for `python 3.11`
---
Tickets:
- [Move on from deprecated pkg_resources api](https://github.com/openedx/edx-ora2/issues/2225)
- [Drop Python 3.8 & Add Support for Python 3.12](https://github.com/openedx/edx-ora2/issues/2230)

2024-10-01 08:46 UTC, farhan requested changes

2024-10-01 08:46 UTC, farhan commented on .github/workflows/pypi-publish.yml
> +          python-version: ${{ matrix.python-version }}
I think we should publish on 1 python version only

2024-10-03 07:59 UTC, farhan approved these changes

2024-10-31 05:26 UTC, ttqureshi commented
> Hi @ttqureshi -- I'm working my way through the PR backlog for this repo, apologies for letting this one go stale! Could you resolve the conflicts so I can review & merge?

sure

2024-10-31 05:55 UTC, ttqureshi commented
conflicts resolved

2024-10-31 07:04 UTC, pomegranited approved these changes
:+1: Thank you for this change @ttqureshi -- it works perfectly.

One nit re the version bump, and could you update the tests to fix coverage?

- [x] I tested this in my tutor dev stack using the Demo course in Studio, LMS, and Preview
- [x] I read through the code
- [x] I checked for accessibility issues by using my keyboard to navigate
- [x] <strike>Includes documentation</strike> N/A
- [x] <strike>User-facing strings are extracted for translation</strike> N/A

2024-10-31 07:04 UTC, pomegranited commented on openassessment/__init__.py
> +__version__ = '7.0.0'
I don't think we need a major version update for this, since there aren't any backwards-incompatible changes.
Just `6.13.0` will do.

2024-11-06 02:51 UTC, pomegranited commented
Hi @ttqureshi -- I'm not sure why I have to keep allowing the CI to run here, but I bet it's frustrating to have to wait for me to know when you've fixed all the errors :(

You can run the tests locally using tox, e.g.

```
python3.11 -m venv venv311
source venv311/bin/activate
pip install tox
TOXENV=quality tox
TOXENV=django42 tox
```

If you want to run the 3.12 tests, use python 3.12 to create your virtualenv.

2024-11-06 04:30 UTC, ttqureshi commented
Thanks @pomegranited for the heads-up! I’ll run the tests locally with tox to catch any errors before pushing. 
Appreciate the tips.

2024-11-07 03:05 UTC, pomegranited commented
@ttqureshi we're so close now!

2024-11-08 02:17 UTC, pomegranited commented
So close @ttqureshi ! Just need a little more code coverage -- the easiest way to spot the missing lines is to look for the inline codecov warnings [like these](https://github.com/openedx/edx-ora2/pull/2238/files#diff-9be7eb4e98c49fd11e65384c14ea6e1c4a159c749e20f7a4f03bf9ceb15fbbcbR137).

2024-11-08 06:29 UTC, ttqureshi commented
> So close @ttqureshi ! Just need a little more code coverage -- the easiest way to spot the missing lines is to look for the inline codecov warnings [like these](https://github.com/openedx/edx-ora2/pull/2238/files#diff-9be7eb4e98c49fd11e65384c14ea6e1c4a159c749e20f7a4f03bf9ceb15fbbcbR137).

alright 👍

2024-11-08 07:17 UTC, ttqureshi commented
@pomegranited I hope it's done now :)

2024-11-12 01:37 UTC, pomegranited commented
@ttqureshi Tests are all green now! Thank you so much for persisting with this change. Merging now :)

2024-11-12 01:40 UTC, merged